global:
  scrape_interval: 36s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "node_memory"
    static_configs:
      - targets: ["node-exporter:9100"]
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: node-exporter:9100
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: (node_memory_MemAvailable_bytes|node_memory_SwapFree_bytes)
        action: keep

  - job_name: "node_disk"
    static_configs:
      - targets: ["node-exporter:9100"]
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: node-exporter:9100
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: (node_disk_.*)
        action: keep

  - job_name: "node_network"
    static_configs:
      - targets: ["node-exporter:9100"]
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: node-exporter:9100
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: (node_network_.*)
        action: keep